package model;
// Generated 22.May.2018 00:25:25 by Hibernate Tools 4.3.1



/**
 * Ogretimuyesi generated by hbm2java
 */public class Ogretimuyesi  implements java.io.Serializable {

     
     private Integer ogretimuyesiid;
     private String sicilno;
     private String adSoyad;
     private String sehir;
     private String telno;

    public Ogretimuyesi() {
    }

	
    public Ogretimuyesi(String sicilno) {
        this.sicilno = sicilno;
    }
    public Ogretimuyesi(String sicilno, String adSoyad, String sehir, String telno) {
       this.sicilno = sicilno;
       this.adSoyad = adSoyad;
       this.sehir = sehir;
       this.telno = telno;
    }
   
    public Integer getOgretimuyesiid() {
        return this.ogretimuyesiid;
    }
    
    public void setOgretimuyesiid(Integer ogretimuyesiid) {
        this.ogretimuyesiid = ogretimuyesiid;
    }
    public String getSicilno() {
        return this.sicilno;
    }
    
    public void setSicilno(String sicilno) {
        this.sicilno = sicilno;
    }
    public String getAdSoyad() {
        return this.adSoyad;
    }
    
    public void setAdSoyad(String adSoyad) {
        this.adSoyad = adSoyad;
    }
    public String getSehir() {
        return this.sehir;
    }
    
    public void setSehir(String sehir) {
        this.sehir = sehir;
    }
    public String getTelno() {
        return this.telno;
    }
    
    public void setTelno(String telno) {
        this.telno = telno;
    }




}


